spring.application.name=url-shortner

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=urlshortner
spring.datasource.password=urlshortner
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Default cache is in-memory. Enable Redis cache via profile: `redis`
spring.cache.type=simple

# App settings
app.cache.shorturl.default-ttl-seconds=86400
app.rate-limit.enabled=true
app.rate-limit.window-seconds=60
app.rate-limit.max-create-per-window=20
app.rate-limit.max-redirect-per-window=120
app.rate-limit.max-analytics-per-window=60

server.port=8080

